version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ruby: circleci/ruby@1.2.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

install_sonarscanner: &install_sonarscanner
  run:
    name: Install SonarScanner
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew install sonar-scanner

install_xcresultparser: &install_xcresultparser
  run:
    name: Install xcresultparser
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew tap a7ex/homebrew-formulae && brew install xcresultparser

jobs:
  show-attached-workspace:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Show attached workspace
          command: ls -la

  show-attached-workspace-mac:
    <<: *defaults
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Show attached workspace
          command: ls -la

  sonar-test:
    <<: *defaults
    steps:
      - sonarcloud/scan

  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - store_artifacts:
          path: test-results.tar.gz
      - persist_to_workspace:
          root: "~"
          paths:
            - project

  scan:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: "~"
      - run: |
          chmod +x bin/xcresultparser
          bin/xcresultparser -c -o xml fastlane/test_output/*.xcresult > sonarqube-generic-coverage.xml
          tar -cvzf test-results.tar.gz fastlane/test_output/*.xcresult
      - store_artifacts:
          path: sonarqube-generic-coverage.xml
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - test:
          filters:
            branches:
              only:
                - na
      - show-attached-workspace:
          requires:
            - test
      - show-attached-workspace-mac:
          requires:
            - test
      - scan:
          requires:
            - test

  sonar-test:
    jobs:
      - sonar-test
