version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  sonarcloud: sonarsource/sonarcloud@1.1.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane build

  analyze:
    working_directory: ~/project
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: "~"
      - run: |
          sh fastlane/xccov-to-generic.sh fastlane/test_output/SwiftSonarWave.xcresult > fastlane/test_output/code-coverage.xml
      - sonarcloud/scan

  run-tests:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - persist_to_workspace:
          root: "~"
          paths:
            - project/fastlane/xccov-to-generic.sh
            - project/fastlane/test_output

workflows:
  main:
    jobs:
      - run-tests
      - analyze:
          requires:
            - run-tests
