version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  sonarcloud: sonarsource/sonarcloud@1.1.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

install_sonarscanner: &install_sonarscanner
  run:
    name: Install SonarScanner
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew install sonar-scanner

jobs:
  analyze:
    working_directory: ~/project
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: "~"
      - sonarcloud/scan

  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - run: |
          bash fastlane/xccov-to-generic.sh fastlane/test_output/SwiftSonarWave.xcresult > code-coverage.xml
      - *install_sonarscanner
      - run: |
          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN
      - store_artifacts:
          path: code-coverage.xml
      - persist_to_workspace:
          root: "~"
          paths:
            - project

workflows:
  main:
    jobs:
      - test
