version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

install_sonarscanner: &install_sonarscanner
  run:
    name: Install SonarScanner
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew install sonar-scanner

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - run: |
          bundle exec slather coverage --sonarqube-xml --ignore '../*' --scheme SwiftSonarWave SwiftSonarWave.xcodeproj
          tar -cvzf test-results.tar.gz fastlane/test_output/*.xcresult
      - *install_sonarscanner
      - run: |
          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN
      - store_artifacts:
          path: test-results.tar.gz
      - store_artifacts:
          path: sonarqube-generic-coverage.xml
      - persist_to_workspace:
          root: "~"
          paths:
            - project

workflows:
  main:
    jobs:
      - test
