version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ruby: circleci/ruby@1.2.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

install_sonarscanner: &install_sonarscanner
  run:
    name: Install SonarScanner
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew install sonar-scanner

install_xcresultparser: &install_xcresultparser
  run:
    name: Install xcresultparser
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew tap a7ex/homebrew-formulae && brew install xcresultparser

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - *install_xcresultparser
      - run: |
          xcresultparser -c -o xml fastlane/test_output/*.xcresult > sonarqube-generic-coverage.xml
          tar -cvzf test-results.tar.gz fastlane/test_output/*.xcresult
      - store_artifacts:
          path: test-results.tar.gz
      - store_artifacts:
          path: sonarqube-generic-coverage.xml
      - persist_to_workspace:
          root: "~"
          paths:
            - project

  scan:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: "~"
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - test
      - scan:
          requires:
            - test
