version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

install_sonarscanner: &install_sonarscanner
  run:
    name: Install SonarScanner
    command: HOMEBREW_NO_AUTO_UPDATE=1 brew install sonar-scanner

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - persist_to_workspace:
          root: "~"
          paths:
            - project

  scan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Convert xcresult files to SonarCloud compatible format
          command: |
            bin/xcresultparser -c -o xml fastlane/test_output/SwiftSonarWave.xcresult > sonarqube-generic-coverage.xml
      - store_artifacts:
          path: sonarqube-generic-coverage.xml
      - *install_sonarscanner
      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.token=$SONAR_TOKEN

workflows:
  main:
    jobs:
      - test
      - scan:
          requires:
            - test
