version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  sonarcloud: sonarsource/sonarcloud@1.1.0

defaults: &defaults
  working_directory: ~/project
  macos:
    xcode: "14.3.1"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane build

  analyze:
    working_directory: ~/project
    docker:
      - image: node:latest
    steps:
      - run: |
          ls -la
      - attach_workspace:
          at: "~"
      - run: |
          ls -la
      - run: |
          cd fastlane
          ls -la
      - run: |
          cd test_output
          ls -la

  run-tests:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - persist_to_workspace:
          root: "~"
          paths:
            - project/fastlane/test_output

  clone:
    <<: *defaults
    steps:
      - checkout
      - run: |
          ls -la
      - run: |
          mkdir fastlane/test_output
          touch fastlane/test_output/SwiftSonarWave.xcresult
      - persist_to_workspace:
          root: "~"
          paths:
            - project

workflows:
  main:
    jobs:
      - clone
      - analyze:
          requires:
            - clone
