version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  sonarcloud: sonarsource/sonarcloud@1.1.0

defaults: &defaults
  macos:
    xcode: "14.3.1"
  shell: /bin/bash --login -o pipefail

jobs:
  build:
    <<: *defaults
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: build
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE

  analyze:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: "~"
      - run: |
          cd ~/project
          sh fastlane/xccov-to-generic.sh fastlane/test_output/SwiftSonarWave.xcresult > fastlane/test_output/code-coverage.xml
      - sonarcloud/scan

  run-tests:
    <<: *defaults
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - persist_to_workspace:
          root: "~"
          paths:
            - project/fastlane/test_output

workflows:
  main:
    jobs:
      - run-tests
      - analyze:
          requires:
            - run-tests
